import type { MonthTheme } from './types';

export const MONTH_THEMES: MonthTheme[] = [
  {
    month: 0,
    name: 'January',
    heroGradientFrom: '#0f172a',
    heroGradientVia: '#1e3a5f',
    heroGradientTo: '#0c2340',
    primaryColor: '#3b82f6',
    accentColor: '#93c5fd',
    ringColor: '#1d4ed8',
    particles: 'snow',
    quote: 'In the depth of winter, I finally learned that there was in me an invincible summer.',
    author: 'Albert Camus',
    emoji: '❄️',
    season: 'winter',
  },
  {
    month: 1,
    name: 'February',
    heroGradientFrom: '#4a0010',
    heroGradientVia: '#881337',
    heroGradientTo: '#9f1239',
    primaryColor: '#f43f5e',
    accentColor: '#fda4af',
    ringColor: '#be123c',
    particles: 'petals',
    quote: 'The best and most beautiful things cannot be seen or touched — they must be felt with the heart.',
    author: 'Helen Keller',
    emoji: '💝',
    season: 'winter',
  },
  {
    month: 2,
    name: 'March',
    heroGradientFrom: '#052e16',
    heroGradientVia: '#166534',
    heroGradientTo: '#15803d',
    primaryColor: '#22c55e',
    accentColor: '#86efac',
    ringColor: '#16a34a',
    particles: 'petals',
    quote: 'No winter lasts forever; no spring skips its turn.',
    author: 'Hal Borland',
    emoji: '🌱',
    season: 'spring',
  },
  {
    month: 3,
    name: 'April',
    heroGradientFrom: '#2e1065',
    heroGradientVia: '#6d28d9',
    heroGradientTo: '#a855f7',
    primaryColor: '#a855f7',
    accentColor: '#d8b4fe',
    ringColor: '#7c3aed',
    particles: 'petals',
    quote: 'April hath put a spirit of youth in everything.',
    author: 'William Shakespeare',
    emoji: '🌸',
    season: 'spring',
  },
  {
    month: 4,
    name: 'May',
    heroGradientFrom: '#14532d',
    heroGradientVia: '#15803d',
    heroGradientTo: '#4d7c0f',
    primaryColor: '#84cc16',
    accentColor: '#bef264',
    ringColor: '#65a30d',
    particles: 'petals',
    quote: 'May holds promise gently in its petals, the sweetest month of all.',
    author: 'Unknown',
    emoji: '🌻',
    season: 'spring',
  },
  {
    month: 5,
    name: 'June',
    heroGradientFrom: '#431407',
    heroGradientVia: '#c2410c',
    heroGradientTo: '#ea580c',
    primaryColor: '#f97316',
    accentColor: '#fdba74',
    ringColor: '#c2410c',
    particles: 'sparkles',
    quote: 'What is one to say about June, the time of perfect young summer.',
    author: 'Gertrude Jekyll',
    emoji: '🌅',
    season: 'summer',
  },
  {
    month: 6,
    name: 'July',
    heroGradientFrom: '#172554',
    heroGradientVia: '#1d4ed8',
    heroGradientTo: '#0369a1',
    primaryColor: '#38bdf8',
    accentColor: '#7dd3fc',
    ringColor: '#0284c7',
    particles: 'sparkles',
    quote: 'July is the heart of summer — full of warmth, light, and the freedom of endless blue skies.',
    author: 'Unknown',
    emoji: '🎆',
    season: 'summer',
  },
  {
    month: 7,
    name: 'August',
    heroGradientFrom: '#422006',
    heroGradientVia: '#a16207',
    heroGradientTo: '#ca8a04',
    primaryColor: '#eab308',
    accentColor: '#fef08a',
    ringColor: '#ca8a04',
    particles: 'sparkles',
    quote: 'Ah, summer, what power you have to make us suffer and like it.',
    author: 'Russell Baker',
    emoji: '🌞',
    season: 'summer',
  },
  {
    month: 8,
    name: 'September',
    heroGradientFrom: '#431407',
    heroGradientVia: '#9a3412',
    heroGradientTo: '#b45309',
    primaryColor: '#f97316',
    accentColor: '#fed7aa',
    ringColor: '#ea580c',
    particles: 'leaves',
    quote: 'September is the most beautiful of words — the most musical, the most meaningful.',
    author: 'Cornell Woolrich',
    emoji: '🍂',
    season: 'fall',
  },
  {
    month: 9,
    name: 'October',
    heroGradientFrom: '#1c0a00',
    heroGradientVia: '#7c2d12',
    heroGradientTo: '#92400e',
    primaryColor: '#ea580c',
    accentColor: '#fb923c',
    ringColor: '#c2410c',
    particles: 'leaves',
    quote: 'October is the month for dreaming.',
    author: 'Richelle Goodrich',
    emoji: '🎃',
    season: 'fall',
  },
  {
    month: 10,
    name: 'November',
    heroGradientFrom: '#1c1917',
    heroGradientVia: '#44403c',
    heroGradientTo: '#78350f',
    primaryColor: '#d97706',
    accentColor: '#fcd34d',
    ringColor: '#b45309',
    particles: 'leaves',
    quote: 'November always seems to me the Norway of the year.',
    author: 'Emily Dickinson',
    emoji: '🍁',
    season: 'fall',
  },
  {
    month: 11,
    name: 'December',
    heroGradientFrom: '#0f172a',
    heroGradientVia: '#14532d',
    heroGradientTo: '#1e3a5f',
    primaryColor: '#22c55e',
    accentColor: '#86efac',
    ringColor: '#15803d',
    particles: 'snow',
    quote: "December's wintery breath is already clouding the pond, frosting the pane, obscuring summer's memory.",
    author: 'John Geddes',
    emoji: '🎄',
    season: 'winter',
  },
];

export function getMonthTheme(month: number): MonthTheme {
  return MONTH_THEMES[month];
}
